server:
  port: 5000

upload:
  provider: "local"          # local | s3 | drive
  folder: "uploads"
  # s3:
  #   bucket: "${S3_BUCKET}"
  #   region: "${S3_REGION}"
  #   accessKeyId: "${S3_ACCESS_KEY_ID}"
  #   secretAccessKey: "${S3_SECRET_ACCESS_KEY}"
  # drive:
  #   credentialsPath: "${DRIVE_CREDENTIALS_PATH}"
  #   folderId: "${DRIVE_FOLDER_ID}"
  #   api_url: "https://www.googleapis.com/drive/v3/files"

ocr:
  provider: "free_ocr"
  api_key: "${FREE_OCR_API_KEY}"
  endpoint: "https://api.ocr.space/parse/image"

llm:
  provider: "openai"   # openai | azure | gemini
  api_key: "${LLM_KEY}"
  llm_model: "gpt-3.5-turbo"      # gpt-4o | gpt-4o-mini | gpt-3.5-turbo
  # endpoint: "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent"
  prompt_template: |
    You are a receipt/invoice parsing AI.

    You receive OCR output from Veryfi in JSON format. The OCR JSON will always include a field "ocr_text" which contains the full raw OCR text.

    OCR Input:
    {{text}}

    Rules:
    - Do NOT guess, normalize, or hallucinate data.
    - Do NOT change spelling, casing, or wording from OCR text.
    - Only extract values if they clearly appear in the OCR text.
    - Vendor (issuer) is always exactly as it appears at the top of the OCR text.
    - Do NOT remove greetings or prefixes like “GOOD”, “HI”, etc.
    - Customer (Bill To) = recipient with prefixes (Mr, Mrs, Ms, Shri, Patient, etc.)
    - Preserve all numeric values exactly.
    - If a field is missing, omit it.
    - Dates = YYYY-MM-DD.
    - Items must keep exact OCR formatting.
    - Always include raw_ocr_text.

    Output JSON ONLY (valid JSON, no markdown):
    {
      "document_type": string,
      "vendor": { "name": string, "address": string, "phone": string },
      "bill_to": { "name": string, "address": string, "phone": string },
      "invoice": { "number": string, "date": string },
      "payment": string,
      "items": [ { "description": string, "quantity": string, "unit_price": string, "total": string } ],
      "subtotal": string,
      "tax": string,
      "total": string,
      "po_number": string,
      "notes": string,
      "raw_ocr_text": string
    }

